server {
  listen 8000;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /docs/;
  }

  location = /docs {
    return 301 /docs/;
  }

  location /docs/ {
    rewrite ^/docs/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }
}
